spring.application.name=forohud

# Configuración base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/foro_hud}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# Permite que Swagger UI envíe cookies (como refreshToken)
springdoc.swagger-ui.with-credentials=true

# No enviar detalles de errores al cliente (seguridad)
server.error.include-stacktrace=never

# JWT secret (puede sobreescribirse con variable de entorno)
api.security.token.secret=${JWT_SECRET:123456789}

server.port=${PORT:8080}